//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Geopoint
{
    public long GeopointId { get; set; }
    public double Latitude { get; set; }
    public double Longitude { get; set; }
    public byte[] ts { get; set; }
    public System.Data.Spatial.DbGeography GeographyPoint { get; set; }
}

public partial class LUT_Asset_Groups
{
    public LUT_Asset_Groups()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
        this.LUT_Sub_Group = new HashSet<LUT_Sub_Group>();
    }

    public int AGrpID { get; set; }
    public string Asset_Groups { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
    public virtual ICollection<LUT_Sub_Group> LUT_Sub_Group { get; set; }
}

public partial class LUT_Asset_History
{
    public int AHID { get; set; }
    public string Asset_History { get; set; }
    public string Description { get; set; }
}

public partial class LUT_Asset_Leased_or_Purchased
{
    public LUT_Asset_Leased_or_Purchased()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int ALPID { get; set; }
    public string Asset_Leased_or_Purchased { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Asset_Leased_To
{
    public int ALID { get; set; }
    public string Asset_Leased_To { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Asset_Manufacturers
{
    public LUT_Asset_Manufacturers()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int MnfID { get; set; }
    public string Asset_Manufacturer { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Asset_Ownership
{
    public int AOID { get; set; }
    public string Asset_Ownership { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Asset_Priority
{
    public int APID { get; set; }
    public string Asset_Priority { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Asset_Under
{
    public int AUID { get; set; }
    public string Asset_Under { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Asset_Users
{
    public int UsID { get; set; }
    public string UserID { get; set; }
    public string password { get; set; }
    public string SecurityQ { get; set; }
    public string SecurityA { get; set; }
    public string EmailID { get; set; }
    public string PhoneNo { get; set; }
    public string NameOfUser { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Assets_Masters
{
    public LUT_Assets_Masters()
    {
        this.LUT_History_of_Asset = new HashSet<LUT_History_of_Asset>();
    }

    public int AID { get; set; }
    public string Name_of_Asset { get; set; }
    public int AGrpID { get; set; }
    public int SGID { get; set; }
    public int MnfID { get; set; }
    public int SPID { get; set; }
    public System.DateTime Date_of_Purchase { get; set; }
    public Nullable<System.DateTime> Date_of_Disposal { get; set; }
    public double Purchase_Price { get; set; }
    public int FID { get; set; }
    public byte[] Photo_of_Asset { get; set; }
    public int CSID { get; set; }
    public int CCID { get; set; }
    public string Model { get; set; }
    public string Sub_Model { get; set; }
    public string Description { get; set; }
    public int TID { get; set; }
    public double Depriciation_Value { get; set; }
    public bool Warranty { get; set; }
    public bool AMC { get; set; }
    public bool PM { get; set; }
    public bool QR { get; set; }
    public bool NFC { get; set; }
    public bool GPS { get; set; }
    public bool Camera { get; set; }
    public bool Barcode { get; set; }
    public int ALPID { get; set; }
    public bool Maintenance { get; set; }
    public bool RFID { get; set; }
    public double Current_Location_X { get; set; }
    public double Current_Location_Y { get; set; }
    public System.Data.Spatial.DbGeography GeographicPoint { get; set; }
    public int MID { get; set; }

    public virtual LUT_Asset_Groups LUT_Asset_Groups { get; set; }
    public virtual LUT_Asset_Leased_or_Purchased LUT_Asset_Leased_or_Purchased { get; set; }
    public virtual LUT_Asset_Manufacturers LUT_Asset_Manufacturers { get; set; }
    public virtual LUT_Current_Status LUT_Current_Status { get; set; }
    public virtual LUT_Frequency LUT_Frequency { get; set; }
    public virtual LUT_Service_Provider_Of_Asset LUT_Service_Provider_Of_Asset { get; set; }
    public virtual LUT_Sub_Group LUT_Sub_Group { get; set; }
    public virtual LUT_Tag_Type LUT_Tag_Type { get; set; }
    public virtual LUT_Current_Condition LUT_Current_Condition { get; set; }
    public virtual LUT_Maintenance LUT_Maintenance { get; set; }
    public virtual ICollection<LUT_History_of_Asset> LUT_History_of_Asset { get; set; }
}

public partial class LUT_Binary
{
    public int UID { get; set; }
    public string Binary { get; set; }
    public string Description { get; set; }
}

public partial class LUT_Binary_Q
{
    public int UID { get; set; }
    public int QID { get; set; }
    public int AID { get; set; }
    public bool Binary { get; set; }
    public string Description { get; set; }
}

public partial class LUT_Camera_Status
{
    public int CaSID { get; set; }
    public string Camera_Status { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Current_Condition
{
    public LUT_Current_Condition()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int CCID { get; set; }
    public string Current_Condition { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Current_Location
{
    public int CLID { get; set; }
    public Nullable<decimal> Current_Location_X { get; set; }
    public decimal Current_Location_Y { get; set; }
    public System.DateTime Last_Modified { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Current_Status
{
    public LUT_Current_Status()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int CSID { get; set; }
    public string Current_Status { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Frequency
{
    public LUT_Frequency()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int FID { get; set; }
    public string Frequency { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Frequency_Of_Annual_Maintenance_Contract
{
    public int FAMCID { get; set; }
    public string Frequency_of_AMC { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_History_of_Asset
{
    public int AHID { get; set; }
    public int AID { get; set; }
    public int HID { get; set; }
    public double Current_Location_X { get; set; }
    public double Current_Location_Y { get; set; }

    public virtual LUT_Assets_Masters LUT_Assets_Masters { get; set; }
}

public partial class LUT_Maintenance
{
    public LUT_Maintenance()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int MID { get; set; }
    public string Maintenance { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Questions
{
    public int QID { get; set; }
    public string Question { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }
}

public partial class LUT_Service_Provider_Of_Asset
{
    public LUT_Service_Provider_Of_Asset()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int SPID { get; set; }
    public string Service_Provider_of_Asset { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Sub_Group
{
    public LUT_Sub_Group()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int SGID { get; set; }
    public int AGrpID { get; set; }
    public string Sub_Group { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual LUT_Asset_Groups LUT_Asset_Groups { get; set; }
    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class LUT_Tag_Type
{
    public LUT_Tag_Type()
    {
        this.LUT_Assets_Masters = new HashSet<LUT_Assets_Masters>();
    }

    public int TID { get; set; }
    public string Tag_Type { get; set; }
    public string Description { get; set; }
    public bool IsDeleted { get; set; }

    public virtual ICollection<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
}

public partial class MarkersN
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public double Lat { get; set; }
    public double Long { get; set; }
    public string Type { get; set; }
}
