//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AssetTaggingEntities : DbContext
{
    public AssetTaggingEntities()
        : base("name=AssetTaggingEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<LUT_Asset_Groups> LUT_Asset_Groups { get; set; }
    public DbSet<LUT_Asset_Leased_or_Purchased> LUT_Asset_Leased_or_Purchased { get; set; }
    public DbSet<LUT_Asset_Manufacturers> LUT_Asset_Manufacturers { get; set; }
    public DbSet<LUT_Asset_Ownership> LUT_Asset_Ownership { get; set; }
    public DbSet<LUT_Asset_Priority> LUT_Asset_Priority { get; set; }
    public DbSet<LUT_Asset_Under> LUT_Asset_Under { get; set; }
    public DbSet<LUT_Asset_Users> LUT_Asset_Users { get; set; }
    public DbSet<LUT_Assets_Masters> LUT_Assets_Masters { get; set; }
    public DbSet<LUT_Binary> LUT_Binary { get; set; }
    public DbSet<LUT_Camera_Status> LUT_Camera_Status { get; set; }
    public DbSet<LUT_Current_Location> LUT_Current_Location { get; set; }
    public DbSet<LUT_Current_Status> LUT_Current_Status { get; set; }
    public DbSet<LUT_Frequency> LUT_Frequency { get; set; }
    public DbSet<LUT_Frequency_Of_Annual_Maintenance_Contract> LUT_Frequency_Of_Annual_Maintenance_Contract { get; set; }
    public DbSet<LUT_Service_Provider_Of_Asset> LUT_Service_Provider_Of_Asset { get; set; }
    public DbSet<LUT_Sub_Group> LUT_Sub_Group { get; set; }
    public DbSet<LUT_Tag_Type> LUT_Tag_Type { get; set; }
    public DbSet<LUT_Asset_Leased_To> LUT_Asset_Leased_To { get; set; }
    public DbSet<LUT_Current_Condition> LUT_Current_Condition { get; set; }
    public DbSet<Geopoint> Geopoints { get; set; }
    public DbSet<LUT_Asset_History> LUT_Asset_History { get; set; }
    public DbSet<LUT_Binary_Q> LUT_Binary_Q { get; set; }
    public DbSet<LUT_Questions> LUT_Questions { get; set; }
    public DbSet<MarkersN> MarkersNs { get; set; }
    public DbSet<LUT_Maintenance> LUT_Maintenance { get; set; }
    public DbSet<LUT_History_of_Asset> LUT_History_of_Asset { get; set; }
}
